{% set name = "mapshader" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mapshader-{{ version }}.tar.gz
  sha256: bdad3b838f0ec853905fcdf40406a8c1744b5697ee6f6b04d926ff4d185b1291

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mapshader = mapshader.commands:main

requirements:
  host:
    - python >=3.6
    - pyct-core
    - pip
  run:
    - python >=3.6
    - xarray-spatial
    - geopandas
    - jinja2
    - rioxarray
    - flask
    - flask-cors
    - rasterio
    - psutil
    - pyct-core
    - descartes
    - jupyter
    - matplotlib
    - pytest

test:
  imports:
    - mapshader
    - mapshader.tests
  commands:
    - pip check
    - mapshader --help
  requires:
    - pip

about:
  home: https://github.com/makepath/mapshader
  summary: Simple Python GIS Web Services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giancastro
