{% set name = "mapshader" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mapshader-{{ version }}.tar.gz
  sha256: 15ea6a445067a29d67c9c4c6bcac8b913d5d244411b30e3e8111ac08e443481e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mapshader = mapshader.commands:main

requirements:
  host:
    - pip
    - pyct-core >=0.4.6
    - python >=3.6
  run:
    - click >=8.0.3
    - descartes >=1.1.0
    - flask >=2.0.2
    - flask-cors >=3.0.10
    - geopandas >=0.10.2
    - jinja2 >=3.0.3
    - jupyter >=1.0.0
    - matplotlib >=3.5.1
    - psutil >=5.9.0
    - pyct-core >=0.4.6
    - python >=3.6
    - pytest >=6.2.5
    - rasterio >=1.2.10
    - rioxarray >=0.9.1
    - xarray-spatial >=0.3.1

test:
  imports:
    - mapshader
    - mapshader.tests
  commands:
    - pip check
    - mapshader --help
  requires:
    - pip

about:
  home: https://github.com/makepath/mapshader
  summary: Simple Python GIS Web Services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - ianthomas23
